/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nkdhny_runtag_WebcamDetector */

#ifndef _Included_nkdhny_runtag_WebcamDetector
#define _Included_nkdhny_runtag_WebcamDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nkdhny_runtag_WebcamDetector
 * Method:    setupNativeDetector
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nkdhny_runtag_WebcamDetector_setupNativeDetector
  (JNIEnv *, jobject);

/*
 * Class:     nkdhny_runtag_WebcamDetector
 * Method:    releaseNativeDetector
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nkdhny_runtag_WebcamDetector_releaseNativeDetector
  (JNIEnv *, jobject);

/*
 * Class:     nkdhny_runtag_WebcamDetector
 * Method:    apply
 * Signature: ()[Lnkdhny/runtag/Tag;
 */
JNIEXPORT jobjectArray JNICALL Java_nkdhny_runtag_WebcamDetector_apply
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
